// Code generated by protoc-gen-go.
// source: github.com/appcelerator/amp/api/rpc/account/permission.proto
// DO NOT EDIT!

/*
Package account is a generated protocol buffer package.

It is generated from these files:
	github.com/appcelerator/amp/api/rpc/account/permission.proto

It has these top-level messages:
	Ressource
	GrantRequest
	ListRequest
	ListReply
	EditRequest
	RevokeRequest
	TransferOwnershipRequest
*/
package account

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/google/api"
import google_protobuf1 "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Ressource struct
type Ressource struct {
	Organization string `protobuf:"bytes,1,opt,name=organization" json:"organization,omitempty"`
	Team         string `protobuf:"bytes,2,opt,name=team" json:"team,omitempty"`
	Level        string `protobuf:"bytes,3,opt,name=level" json:"level,omitempty"`
	ResourceId   string `protobuf:"bytes,4,opt,name=resource_id,json=resourceId" json:"resource_id,omitempty"`
}

func (m *Ressource) Reset()                    { *m = Ressource{} }
func (m *Ressource) String() string            { return proto.CompactTextString(m) }
func (*Ressource) ProtoMessage()               {}
func (*Ressource) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Ressource) GetOrganization() string {
	if m != nil {
		return m.Organization
	}
	return ""
}

func (m *Ressource) GetTeam() string {
	if m != nil {
		return m.Team
	}
	return ""
}

func (m *Ressource) GetLevel() string {
	if m != nil {
		return m.Level
	}
	return ""
}

func (m *Ressource) GetResourceId() string {
	if m != nil {
		return m.ResourceId
	}
	return ""
}

// Grant function
type GrantRequest struct {
	Ressource *Ressource `protobuf:"bytes,1,opt,name=ressource" json:"ressource,omitempty"`
}

func (m *GrantRequest) Reset()                    { *m = GrantRequest{} }
func (m *GrantRequest) String() string            { return proto.CompactTextString(m) }
func (*GrantRequest) ProtoMessage()               {}
func (*GrantRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GrantRequest) GetRessource() *Ressource {
	if m != nil {
		return m.Ressource
	}
	return nil
}

// List function
type ListRequest struct {
	Organization string `protobuf:"bytes,1,opt,name=organization" json:"organization,omitempty"`
	Team         string `protobuf:"bytes,2,opt,name=team" json:"team,omitempty"`
	Level        string `protobuf:"bytes,3,opt,name=level" json:"level,omitempty"`
	ResourceId   string `protobuf:"bytes,4,opt,name=resource_id,json=resourceId" json:"resource_id,omitempty"`
}

func (m *ListRequest) Reset()                    { *m = ListRequest{} }
func (m *ListRequest) String() string            { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()               {}
func (*ListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ListRequest) GetOrganization() string {
	if m != nil {
		return m.Organization
	}
	return ""
}

func (m *ListRequest) GetTeam() string {
	if m != nil {
		return m.Team
	}
	return ""
}

func (m *ListRequest) GetLevel() string {
	if m != nil {
		return m.Level
	}
	return ""
}

func (m *ListRequest) GetResourceId() string {
	if m != nil {
		return m.ResourceId
	}
	return ""
}

type ListReply struct {
	Ressources []*Ressource `protobuf:"bytes,1,rep,name=ressources" json:"ressources,omitempty"`
}

func (m *ListReply) Reset()                    { *m = ListReply{} }
func (m *ListReply) String() string            { return proto.CompactTextString(m) }
func (*ListReply) ProtoMessage()               {}
func (*ListReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ListReply) GetRessources() []*Ressource {
	if m != nil {
		return m.Ressources
	}
	return nil
}

// Edit function
type EditRequest struct {
	Ressource *Ressource `protobuf:"bytes,1,opt,name=ressource" json:"ressource,omitempty"`
}

func (m *EditRequest) Reset()                    { *m = EditRequest{} }
func (m *EditRequest) String() string            { return proto.CompactTextString(m) }
func (*EditRequest) ProtoMessage()               {}
func (*EditRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *EditRequest) GetRessource() *Ressource {
	if m != nil {
		return m.Ressource
	}
	return nil
}

// Revoke function
type RevokeRequest struct {
	Ressource *Ressource `protobuf:"bytes,1,opt,name=ressource" json:"ressource,omitempty"`
}

func (m *RevokeRequest) Reset()                    { *m = RevokeRequest{} }
func (m *RevokeRequest) String() string            { return proto.CompactTextString(m) }
func (*RevokeRequest) ProtoMessage()               {}
func (*RevokeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *RevokeRequest) GetRessource() *Ressource {
	if m != nil {
		return m.Ressource
	}
	return nil
}

// TransferOwnership function
type TransferOwnershipRequest struct {
	Organization string `protobuf:"bytes,1,opt,name=organization" json:"organization,omitempty"`
	Team         string `protobuf:"bytes,2,opt,name=team" json:"team,omitempty"`
	ResourceId   string `protobuf:"bytes,3,opt,name=resource_id,json=resourceId" json:"resource_id,omitempty"`
}

func (m *TransferOwnershipRequest) Reset()                    { *m = TransferOwnershipRequest{} }
func (m *TransferOwnershipRequest) String() string            { return proto.CompactTextString(m) }
func (*TransferOwnershipRequest) ProtoMessage()               {}
func (*TransferOwnershipRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *TransferOwnershipRequest) GetOrganization() string {
	if m != nil {
		return m.Organization
	}
	return ""
}

func (m *TransferOwnershipRequest) GetTeam() string {
	if m != nil {
		return m.Team
	}
	return ""
}

func (m *TransferOwnershipRequest) GetResourceId() string {
	if m != nil {
		return m.ResourceId
	}
	return ""
}

func init() {
	proto.RegisterType((*Ressource)(nil), "account.Ressource")
	proto.RegisterType((*GrantRequest)(nil), "account.GrantRequest")
	proto.RegisterType((*ListRequest)(nil), "account.ListRequest")
	proto.RegisterType((*ListReply)(nil), "account.ListReply")
	proto.RegisterType((*EditRequest)(nil), "account.EditRequest")
	proto.RegisterType((*RevokeRequest)(nil), "account.RevokeRequest")
	proto.RegisterType((*TransferOwnershipRequest)(nil), "account.TransferOwnershipRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for PermissionService service

type PermissionServiceClient interface {
	Grant(ctx context.Context, in *GrantRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListReply, error)
	Edit(ctx context.Context, in *EditRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	Revoke(ctx context.Context, in *RevokeRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	TransferOwnership(ctx context.Context, in *TransferOwnershipRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
}

type permissionServiceClient struct {
	cc *grpc.ClientConn
}

func NewPermissionServiceClient(cc *grpc.ClientConn) PermissionServiceClient {
	return &permissionServiceClient{cc}
}

func (c *permissionServiceClient) Grant(ctx context.Context, in *GrantRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/account.PermissionService/Grant", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionServiceClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListReply, error) {
	out := new(ListReply)
	err := grpc.Invoke(ctx, "/account.PermissionService/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionServiceClient) Edit(ctx context.Context, in *EditRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/account.PermissionService/Edit", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionServiceClient) Revoke(ctx context.Context, in *RevokeRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/account.PermissionService/Revoke", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionServiceClient) TransferOwnership(ctx context.Context, in *TransferOwnershipRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/account.PermissionService/TransferOwnership", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PermissionService service

type PermissionServiceServer interface {
	Grant(context.Context, *GrantRequest) (*google_protobuf1.Empty, error)
	List(context.Context, *ListRequest) (*ListReply, error)
	Edit(context.Context, *EditRequest) (*google_protobuf1.Empty, error)
	Revoke(context.Context, *RevokeRequest) (*google_protobuf1.Empty, error)
	TransferOwnership(context.Context, *TransferOwnershipRequest) (*google_protobuf1.Empty, error)
}

func RegisterPermissionServiceServer(s *grpc.Server, srv PermissionServiceServer) {
	s.RegisterService(&_PermissionService_serviceDesc, srv)
}

func _PermissionService_Grant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionServiceServer).Grant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.PermissionService/Grant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionServiceServer).Grant(ctx, req.(*GrantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.PermissionService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionServiceServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionService_Edit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionServiceServer).Edit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.PermissionService/Edit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionServiceServer).Edit(ctx, req.(*EditRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionService_Revoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionServiceServer).Revoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.PermissionService/Revoke",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionServiceServer).Revoke(ctx, req.(*RevokeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionService_TransferOwnership_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferOwnershipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionServiceServer).TransferOwnership(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.PermissionService/TransferOwnership",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionServiceServer).TransferOwnership(ctx, req.(*TransferOwnershipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PermissionService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "account.PermissionService",
	HandlerType: (*PermissionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Grant",
			Handler:    _PermissionService_Grant_Handler,
		},
		{
			MethodName: "List",
			Handler:    _PermissionService_List_Handler,
		},
		{
			MethodName: "Edit",
			Handler:    _PermissionService_Edit_Handler,
		},
		{
			MethodName: "Revoke",
			Handler:    _PermissionService_Revoke_Handler,
		},
		{
			MethodName: "TransferOwnership",
			Handler:    _PermissionService_TransferOwnership_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/appcelerator/amp/api/rpc/account/permission.proto",
}

func init() {
	proto.RegisterFile("github.com/appcelerator/amp/api/rpc/account/permission.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 518 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xbc, 0x93, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x80, 0xe5, 0x26, 0x29, 0xca, 0xa4, 0x1c, 0x3a, 0x2a, 0x95, 0x15, 0x90, 0x28, 0x3e, 0xa1,
	0x1e, 0x6c, 0x9a, 0x9e, 0x40, 0xa0, 0x02, 0x52, 0xc4, 0x8f, 0x90, 0xa8, 0x02, 0x57, 0x54, 0x6d,
	0x9c, 0x69, 0xb2, 0xaa, 0xed, 0x5d, 0x76, 0xd7, 0x41, 0x29, 0xe4, 0xc2, 0x89, 0x3b, 0x17, 0x4e,
	0xf0, 0x50, 0xbc, 0x02, 0x17, 0xde, 0x02, 0x79, 0x9d, 0x98, 0x6d, 0xc0, 0x12, 0xa2, 0xd0, 0x5b,
	0x76, 0x66, 0x33, 0xf3, 0xcd, 0xec, 0x67, 0xb8, 0x3b, 0xe6, 0x66, 0x92, 0x0f, 0xc3, 0x58, 0xa4,
	0x11, 0x93, 0x32, 0xa6, 0x84, 0x14, 0x33, 0x42, 0x45, 0x2c, 0x95, 0x11, 0x93, 0x3c, 0x52, 0x32,
	0x8e, 0x58, 0x1c, 0x8b, 0x3c, 0x33, 0x91, 0x24, 0x95, 0x72, 0xad, 0xb9, 0xc8, 0x42, 0xa9, 0x84,
	0x11, 0x78, 0x69, 0x91, 0xe9, 0x5e, 0x1b, 0x0b, 0x31, 0x4e, 0xc8, 0xfe, 0x83, 0x65, 0x99, 0x30,
	0xcc, 0x70, 0x91, 0xe9, 0xf2, 0x5a, 0xf7, 0xea, 0x22, 0x6b, 0x4f, 0xc3, 0xfc, 0x38, 0xa2, 0x54,
	0x9a, 0x59, 0x99, 0x0c, 0x4e, 0xa1, 0x3d, 0x20, 0xad, 0x45, 0xae, 0x62, 0xc2, 0x00, 0x36, 0x84,
	0x1a, 0xb3, 0x8c, 0x9f, 0xda, 0x02, 0xbe, 0xb7, 0xe3, 0xdd, 0x6c, 0x0f, 0xce, 0xc4, 0x10, 0xa1,
	0x69, 0x88, 0xa5, 0xfe, 0x9a, 0xcd, 0xd9, 0xdf, 0xb8, 0x05, 0xad, 0x84, 0xa6, 0x94, 0xf8, 0x0d,
	0x1b, 0x2c, 0x0f, 0x78, 0x1d, 0x3a, 0x8a, 0xca, 0xca, 0x47, 0x7c, 0xe4, 0x37, 0x6d, 0x0e, 0x96,
	0xa1, 0x27, 0xa3, 0xe0, 0x3e, 0x6c, 0x3c, 0x52, 0x2c, 0x33, 0x03, 0x7a, 0x9d, 0x93, 0x36, 0x78,
	0x0b, 0xda, 0x6a, 0xc9, 0x62, 0x7b, 0x77, 0x7a, 0x18, 0x2e, 0x66, 0x0c, 0x2b, 0xca, 0xc1, 0xcf,
	0x4b, 0xc1, 0x3b, 0xe8, 0x3c, 0xe3, 0xba, 0x2a, 0x70, 0xc1, 0xfc, 0x07, 0xd0, 0x2e, 0xbb, 0xcb,
	0x64, 0x86, 0x3d, 0x80, 0x8a, 0x4b, 0xfb, 0xde, 0x4e, 0xa3, 0x86, 0xde, 0xb9, 0x15, 0x1c, 0x40,
	0xa7, 0x3f, 0xe2, 0xe7, 0x98, 0xff, 0x01, 0x5c, 0x1e, 0xd0, 0x54, 0x9c, 0xd0, 0xdf, 0x97, 0xd0,
	0xe0, 0xbf, 0x54, 0x2c, 0xd3, 0xc7, 0xa4, 0x9e, 0xbf, 0xc9, 0x48, 0xe9, 0x09, 0x97, 0xe7, 0xdd,
	0xe7, 0xca, 0xe6, 0x1a, 0xab, 0x9b, 0xeb, 0x7d, 0x6f, 0xc1, 0xe6, 0x61, 0xa5, 0xf3, 0x0b, 0x52,
	0x53, 0x1e, 0x13, 0x7e, 0xf0, 0xa0, 0x65, 0x85, 0xc0, 0x2b, 0x15, 0xb3, 0x2b, 0x48, 0x77, 0x3b,
	0x2c, 0x55, 0x0e, 0x97, 0x2a, 0x87, 0xfd, 0x42, 0xe5, 0xe0, 0xf0, 0xfd, 0xd7, 0x6f, 0x1f, 0xd7,
	0x9e, 0x06, 0xfd, 0x68, 0xba, 0x57, 0x7d, 0x2e, 0x6f, 0xab, 0x19, 0x43, 0x17, 0x78, 0x1e, 0x15,
	0x88, 0x6e, 0xb6, 0x38, 0xcf, 0x9d, 0xaf, 0xeb, 0x8e, 0xb7, 0x8b, 0x27, 0xd0, 0x2c, 0x9e, 0x16,
	0xb7, 0x2a, 0x10, 0xc7, 0xb3, 0x2e, 0xae, 0x44, 0x65, 0x32, 0x0b, 0x6e, 0x5b, 0x86, 0x7d, 0xdc,
	0x3b, 0xc3, 0xf0, 0xbb, 0xce, 0xab, 0xfd, 0xf0, 0xb3, 0x07, 0xcd, 0xc2, 0x03, 0xa7, 0x9b, 0xa3,
	0x45, 0xed, 0xd4, 0x13, 0xdb, 0x71, 0xd8, 0x7d, 0xf5, 0x4f, 0xa6, 0x76, 0x73, 0xce, 0xe3, 0xcd,
	0x8b, 0x6d, 0x7c, 0xf1, 0x60, 0xbd, 0xf4, 0x0c, 0xb7, 0x1d, 0x9b, 0x1c, 0xf1, 0x6a, 0x21, 0xc9,
	0x42, 0x1e, 0xed, 0xfe, 0x5f, 0x48, 0xfc, 0xe4, 0xc1, 0xe6, 0x2f, 0x1a, 0xe3, 0x8d, 0x0a, 0xb6,
	0x4e, 0xf1, 0x5a, 0xee, 0xc7, 0x96, 0xfb, 0x61, 0x70, 0xef, 0x0f, 0x9f, 0xd3, 0x2c, 0x1a, 0x58,
	0x42, 0x77, 0x79, 0xc3, 0x75, 0x5b, 0x79, 0xff, 0x47, 0x00, 0x00, 0x00, 0xff, 0xff, 0x4c, 0x89,
	0x0e, 0x27, 0xec, 0x05, 0x00, 0x00,
}
