// Code generated by protoc-gen-go.
// source: github.com/appcelerator/amp/api/rpc/account/team.proto
// DO NOT EDIT!

/*
Package account is a generated protocol buffer package.

It is generated from these files:
	github.com/appcelerator/amp/api/rpc/account/team.proto

It has these top-level messages:
	CreateTeamRequest
	ListTeamRequest
	ListTeamReply
	EditTeamRequest
	GetTeamDetailsRequest
	GetTeamDetailsReply
	DeleteTeamRequest
	AddTeamMembershipsRequest
	DeleteTeamMembershipsRequest
*/
package account

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/google/api"
import google_protobuf1 "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Create function
type CreateTeamRequest struct {
	Organization string `protobuf:"bytes,1,opt,name=organization" json:"organization,omitempty"`
	Name         string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Description  string `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
}

func (m *CreateTeamRequest) Reset()                    { *m = CreateTeamRequest{} }
func (m *CreateTeamRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateTeamRequest) ProtoMessage()               {}
func (*CreateTeamRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CreateTeamRequest) GetOrganization() string {
	if m != nil {
		return m.Organization
	}
	return ""
}

func (m *CreateTeamRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateTeamRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

// List function
type ListTeamRequest struct {
	Organization string `protobuf:"bytes,1,opt,name=organization" json:"organization,omitempty"`
}

func (m *ListTeamRequest) Reset()                    { *m = ListTeamRequest{} }
func (m *ListTeamRequest) String() string            { return proto.CompactTextString(m) }
func (*ListTeamRequest) ProtoMessage()               {}
func (*ListTeamRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ListTeamRequest) GetOrganization() string {
	if m != nil {
		return m.Organization
	}
	return ""
}

type ListTeamReply struct {
	TeamNames []string `protobuf:"bytes,2,rep,name=team_names,json=teamNames" json:"team_names,omitempty"`
}

func (m *ListTeamReply) Reset()                    { *m = ListTeamReply{} }
func (m *ListTeamReply) String() string            { return proto.CompactTextString(m) }
func (*ListTeamReply) ProtoMessage()               {}
func (*ListTeamReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ListTeamReply) GetTeamNames() []string {
	if m != nil {
		return m.TeamNames
	}
	return nil
}

// Edit function
type EditTeamRequest struct {
	Organization string `protobuf:"bytes,1,opt,name=organization" json:"organization,omitempty"`
	Name         string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Description  string `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
}

func (m *EditTeamRequest) Reset()                    { *m = EditTeamRequest{} }
func (m *EditTeamRequest) String() string            { return proto.CompactTextString(m) }
func (*EditTeamRequest) ProtoMessage()               {}
func (*EditTeamRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *EditTeamRequest) GetOrganization() string {
	if m != nil {
		return m.Organization
	}
	return ""
}

func (m *EditTeamRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EditTeamRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

// GetDetails function
type GetTeamDetailsRequest struct {
	Organization string `protobuf:"bytes,1,opt,name=organization" json:"organization,omitempty"`
	Name         string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *GetTeamDetailsRequest) Reset()                    { *m = GetTeamDetailsRequest{} }
func (m *GetTeamDetailsRequest) String() string            { return proto.CompactTextString(m) }
func (*GetTeamDetailsRequest) ProtoMessage()               {}
func (*GetTeamDetailsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GetTeamDetailsRequest) GetOrganization() string {
	if m != nil {
		return m.Organization
	}
	return ""
}

func (m *GetTeamDetailsRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetTeamDetailsReply struct {
	Organization string   `protobuf:"bytes,1,opt,name=organization" json:"organization,omitempty"`
	Name         string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Description  string   `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	Members      []string `protobuf:"bytes,4,rep,name=members" json:"members,omitempty"`
}

func (m *GetTeamDetailsReply) Reset()                    { *m = GetTeamDetailsReply{} }
func (m *GetTeamDetailsReply) String() string            { return proto.CompactTextString(m) }
func (*GetTeamDetailsReply) ProtoMessage()               {}
func (*GetTeamDetailsReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *GetTeamDetailsReply) GetOrganization() string {
	if m != nil {
		return m.Organization
	}
	return ""
}

func (m *GetTeamDetailsReply) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetTeamDetailsReply) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *GetTeamDetailsReply) GetMembers() []string {
	if m != nil {
		return m.Members
	}
	return nil
}

// Delete function
type DeleteTeamRequest struct {
	Organization string `protobuf:"bytes,1,opt,name=organization" json:"organization,omitempty"`
	Name         string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *DeleteTeamRequest) Reset()                    { *m = DeleteTeamRequest{} }
func (m *DeleteTeamRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteTeamRequest) ProtoMessage()               {}
func (*DeleteTeamRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *DeleteTeamRequest) GetOrganization() string {
	if m != nil {
		return m.Organization
	}
	return ""
}

func (m *DeleteTeamRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// AddMembership function
type AddTeamMembershipsRequest struct {
	Organization string   `protobuf:"bytes,1,opt,name=organization" json:"organization,omitempty"`
	Name         string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Members      []string `protobuf:"bytes,3,rep,name=Members" json:"Members,omitempty"`
}

func (m *AddTeamMembershipsRequest) Reset()                    { *m = AddTeamMembershipsRequest{} }
func (m *AddTeamMembershipsRequest) String() string            { return proto.CompactTextString(m) }
func (*AddTeamMembershipsRequest) ProtoMessage()               {}
func (*AddTeamMembershipsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *AddTeamMembershipsRequest) GetOrganization() string {
	if m != nil {
		return m.Organization
	}
	return ""
}

func (m *AddTeamMembershipsRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AddTeamMembershipsRequest) GetMembers() []string {
	if m != nil {
		return m.Members
	}
	return nil
}

// DeleteMembership function
type DeleteTeamMembershipsRequest struct {
	Organization string   `protobuf:"bytes,1,opt,name=organization" json:"organization,omitempty"`
	Name         string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Members      []string `protobuf:"bytes,3,rep,name=Members" json:"Members,omitempty"`
}

func (m *DeleteTeamMembershipsRequest) Reset()                    { *m = DeleteTeamMembershipsRequest{} }
func (m *DeleteTeamMembershipsRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteTeamMembershipsRequest) ProtoMessage()               {}
func (*DeleteTeamMembershipsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *DeleteTeamMembershipsRequest) GetOrganization() string {
	if m != nil {
		return m.Organization
	}
	return ""
}

func (m *DeleteTeamMembershipsRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DeleteTeamMembershipsRequest) GetMembers() []string {
	if m != nil {
		return m.Members
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateTeamRequest)(nil), "account.CreateTeamRequest")
	proto.RegisterType((*ListTeamRequest)(nil), "account.ListTeamRequest")
	proto.RegisterType((*ListTeamReply)(nil), "account.ListTeamReply")
	proto.RegisterType((*EditTeamRequest)(nil), "account.EditTeamRequest")
	proto.RegisterType((*GetTeamDetailsRequest)(nil), "account.GetTeamDetailsRequest")
	proto.RegisterType((*GetTeamDetailsReply)(nil), "account.GetTeamDetailsReply")
	proto.RegisterType((*DeleteTeamRequest)(nil), "account.DeleteTeamRequest")
	proto.RegisterType((*AddTeamMembershipsRequest)(nil), "account.AddTeamMembershipsRequest")
	proto.RegisterType((*DeleteTeamMembershipsRequest)(nil), "account.DeleteTeamMembershipsRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for TeamService service

type TeamServiceClient interface {
	Create(ctx context.Context, in *CreateTeamRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	List(ctx context.Context, in *ListTeamRequest, opts ...grpc.CallOption) (*ListTeamReply, error)
	Edit(ctx context.Context, in *EditTeamRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	GetDetails(ctx context.Context, in *GetTeamDetailsRequest, opts ...grpc.CallOption) (*GetTeamDetailsReply, error)
	Delete(ctx context.Context, in *DeleteTeamRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	AddMemberships(ctx context.Context, in *AddTeamMembershipsRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	DeleteMemberships(ctx context.Context, in *DeleteTeamMembershipsRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
}

type teamServiceClient struct {
	cc *grpc.ClientConn
}

func NewTeamServiceClient(cc *grpc.ClientConn) TeamServiceClient {
	return &teamServiceClient{cc}
}

func (c *teamServiceClient) Create(ctx context.Context, in *CreateTeamRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/account.TeamService/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teamServiceClient) List(ctx context.Context, in *ListTeamRequest, opts ...grpc.CallOption) (*ListTeamReply, error) {
	out := new(ListTeamReply)
	err := grpc.Invoke(ctx, "/account.TeamService/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teamServiceClient) Edit(ctx context.Context, in *EditTeamRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/account.TeamService/Edit", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teamServiceClient) GetDetails(ctx context.Context, in *GetTeamDetailsRequest, opts ...grpc.CallOption) (*GetTeamDetailsReply, error) {
	out := new(GetTeamDetailsReply)
	err := grpc.Invoke(ctx, "/account.TeamService/GetDetails", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teamServiceClient) Delete(ctx context.Context, in *DeleteTeamRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/account.TeamService/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teamServiceClient) AddMemberships(ctx context.Context, in *AddTeamMembershipsRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/account.TeamService/AddMemberships", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teamServiceClient) DeleteMemberships(ctx context.Context, in *DeleteTeamMembershipsRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/account.TeamService/DeleteMemberships", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for TeamService service

type TeamServiceServer interface {
	Create(context.Context, *CreateTeamRequest) (*google_protobuf1.Empty, error)
	List(context.Context, *ListTeamRequest) (*ListTeamReply, error)
	Edit(context.Context, *EditTeamRequest) (*google_protobuf1.Empty, error)
	GetDetails(context.Context, *GetTeamDetailsRequest) (*GetTeamDetailsReply, error)
	Delete(context.Context, *DeleteTeamRequest) (*google_protobuf1.Empty, error)
	AddMemberships(context.Context, *AddTeamMembershipsRequest) (*google_protobuf1.Empty, error)
	DeleteMemberships(context.Context, *DeleteTeamMembershipsRequest) (*google_protobuf1.Empty, error)
}

func RegisterTeamServiceServer(s *grpc.Server, srv TeamServiceServer) {
	s.RegisterService(&_TeamService_serviceDesc, srv)
}

func _TeamService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTeamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.TeamService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamServiceServer).Create(ctx, req.(*CreateTeamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeamService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTeamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.TeamService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamServiceServer).List(ctx, req.(*ListTeamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeamService_Edit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditTeamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamServiceServer).Edit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.TeamService/Edit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamServiceServer).Edit(ctx, req.(*EditTeamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeamService_GetDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTeamDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamServiceServer).GetDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.TeamService/GetDetails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamServiceServer).GetDetails(ctx, req.(*GetTeamDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeamService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTeamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.TeamService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamServiceServer).Delete(ctx, req.(*DeleteTeamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeamService_AddMemberships_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTeamMembershipsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamServiceServer).AddMemberships(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.TeamService/AddMemberships",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamServiceServer).AddMemberships(ctx, req.(*AddTeamMembershipsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeamService_DeleteMemberships_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTeamMembershipsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamServiceServer).DeleteMemberships(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.TeamService/DeleteMemberships",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamServiceServer).DeleteMemberships(ctx, req.(*DeleteTeamMembershipsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TeamService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "account.TeamService",
	HandlerType: (*TeamServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _TeamService_Create_Handler,
		},
		{
			MethodName: "List",
			Handler:    _TeamService_List_Handler,
		},
		{
			MethodName: "Edit",
			Handler:    _TeamService_Edit_Handler,
		},
		{
			MethodName: "GetDetails",
			Handler:    _TeamService_GetDetails_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _TeamService_Delete_Handler,
		},
		{
			MethodName: "AddMemberships",
			Handler:    _TeamService_AddMemberships_Handler,
		},
		{
			MethodName: "DeleteMemberships",
			Handler:    _TeamService_DeleteMemberships_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/appcelerator/amp/api/rpc/account/team.proto",
}

func init() {
	proto.RegisterFile("github.com/appcelerator/amp/api/rpc/account/team.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 545 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xbc, 0x94, 0x5f, 0x6b, 0x13, 0x41,
	0x10, 0xc0, 0xb9, 0x24, 0xa4, 0x64, 0xaa, 0x96, 0xae, 0x58, 0xce, 0x33, 0x6a, 0x5c, 0x50, 0x43,
	0x84, 0x3b, 0xd2, 0x62, 0x41, 0xf1, 0xa5, 0xd8, 0xd2, 0x07, 0xff, 0x41, 0xf4, 0x5d, 0x36, 0x77,
	0x63, 0xba, 0xf4, 0xf6, 0x76, 0xbd, 0xdb, 0x14, 0xd2, 0xd2, 0x17, 0xdf, 0x14, 0x7c, 0xf2, 0xa3,
	0x89, 0xdf, 0xc0, 0x0f, 0x22, 0xbb, 0x77, 0x49, 0xcf, 0x34, 0xa1, 0x09, 0xd5, 0xbe, 0x65, 0x67,
	0xee, 0xe6, 0x37, 0x33, 0xd9, 0xdf, 0xc1, 0xf6, 0x80, 0xeb, 0x83, 0x61, 0xdf, 0x0f, 0xa5, 0x08,
	0x98, 0x52, 0x21, 0xc6, 0x98, 0x32, 0x2d, 0xd3, 0x80, 0x09, 0x15, 0x30, 0xc5, 0x83, 0x54, 0x85,
	0x01, 0x0b, 0x43, 0x39, 0x4c, 0x74, 0xa0, 0x91, 0x09, 0x5f, 0xa5, 0x52, 0x4b, 0xb2, 0x52, 0xc4,
	0xbc, 0xe6, 0x40, 0xca, 0x41, 0x8c, 0xf6, 0x59, 0x96, 0x24, 0x52, 0x33, 0xcd, 0x65, 0x92, 0xe5,
	0x8f, 0x79, 0x77, 0x8a, 0xac, 0x3d, 0xf5, 0x87, 0x9f, 0x02, 0x14, 0x4a, 0x8f, 0xf2, 0x24, 0x15,
	0xb0, 0xfe, 0x32, 0x45, 0xa6, 0xf1, 0x03, 0x32, 0xd1, 0xc3, 0xcf, 0x43, 0xcc, 0x34, 0xa1, 0x70,
	0x4d, 0xa6, 0x03, 0x96, 0xf0, 0x63, 0x5b, 0xc8, 0x75, 0x5a, 0x4e, 0xbb, 0xd1, 0xfb, 0x2b, 0x46,
	0x08, 0xd4, 0x12, 0x26, 0xd0, 0xad, 0xd8, 0x9c, 0xfd, 0x4d, 0x5a, 0xb0, 0x1a, 0x61, 0x16, 0xa6,
	0x5c, 0xd9, 0xd7, 0xaa, 0x36, 0x55, 0x0e, 0xd1, 0xa7, 0xb0, 0xf6, 0x9a, 0x67, 0x7a, 0x49, 0x18,
	0xf5, 0xe1, 0xfa, 0xd9, 0x6b, 0x2a, 0x1e, 0x91, 0xbb, 0x00, 0x66, 0x11, 0x1f, 0x0d, 0x36, 0x73,
	0x2b, 0xad, 0x6a, 0xbb, 0xd1, 0x6b, 0x98, 0xc8, 0x5b, 0x13, 0xa0, 0x87, 0xb0, 0xb6, 0x17, 0x71,
	0x7d, 0x35, 0x33, 0xbd, 0x83, 0x5b, 0xfb, 0x68, 0x59, 0xbb, 0xa8, 0x19, 0x8f, 0xb3, 0x4b, 0x22,
	0xe9, 0x57, 0x07, 0x6e, 0x4e, 0x57, 0x34, 0x43, 0xff, 0xb7, 0x11, 0x88, 0x0b, 0x2b, 0x02, 0x45,
	0x1f, 0xd3, 0xcc, 0xad, 0xd9, 0x5d, 0x8e, 0x8f, 0xf4, 0x15, 0xac, 0xef, 0x62, 0x8c, 0xff, 0xe4,
	0x7e, 0x50, 0x01, 0xb7, 0x77, 0xa2, 0xc8, 0x54, 0x7a, 0x93, 0x97, 0x3f, 0xe0, 0xea, 0xb2, 0xdb,
	0x32, 0xbd, 0x17, 0xd5, 0xdc, 0x6a, 0xde, 0x7b, 0x71, 0xa4, 0x0a, 0x9a, 0x67, 0xbd, 0x5f, 0x05,
	0x71, 0xf3, 0x57, 0x1d, 0x56, 0x0d, 0xec, 0x3d, 0xa6, 0x47, 0x3c, 0x44, 0x22, 0xa1, 0x9e, 0xdb,
	0x45, 0x3c, 0xbf, 0x90, 0xd5, 0x3f, 0xa7, 0x9b, 0xb7, 0xe1, 0xe7, 0x86, 0xfa, 0x63, 0x43, 0xfd,
	0x3d, 0x63, 0x28, 0xed, 0x7e, 0xf9, 0xf9, 0xfb, 0x47, 0xe5, 0x09, 0x7d, 0x14, 0x1c, 0x75, 0x27,
	0xfe, 0x9f, 0x94, 0xdb, 0x3b, 0xb5, 0x9f, 0x83, 0xe0, 0xc4, 0xb4, 0x75, 0xfa, 0xdc, 0xe9, 0x10,
	0x06, 0x35, 0x23, 0x0a, 0x71, 0x27, 0xb8, 0x29, 0xdd, 0xbc, 0x8d, 0x19, 0x19, 0x15, 0x8f, 0xe8,
	0x63, 0x0b, 0x7b, 0x40, 0xee, 0x5f, 0x00, 0x23, 0x87, 0x50, 0x33, 0x6e, 0x95, 0x10, 0x53, 0xaa,
	0x5d, 0x34, 0x8f, 0xb7, 0xc4, 0x3c, 0xc7, 0x00, 0xfb, 0xa8, 0x0b, 0x0b, 0xc8, 0xbd, 0x09, 0x72,
	0xa6, 0x70, 0x5e, 0x73, 0x6e, 0xde, 0x4c, 0xe8, 0x5b, 0x7c, 0x9b, 0x2c, 0x88, 0x27, 0x31, 0xd4,
	0xf3, 0xeb, 0x53, 0xfa, 0xf3, 0xce, 0xb9, 0x30, 0x77, 0xd8, 0x82, 0xd6, 0x59, 0x94, 0xf6, 0xcd,
	0x81, 0x1b, 0x3b, 0x51, 0x54, 0xba, 0xa6, 0x84, 0x4e, 0xb0, 0x73, 0xad, 0x99, 0x8b, 0x7f, 0x61,
	0xf1, 0xdb, 0x9b, 0xdd, 0xc5, 0xf0, 0x81, 0x98, 0x94, 0x36, 0x6b, 0xff, 0xee, 0x8c, 0xb5, 0x2f,
	0xf7, 0xf3, 0x70, 0xc6, 0x1a, 0x96, 0x68, 0xe9, 0x99, 0x6d, 0x69, 0xab, 0xb3, 0x7c, 0x4b, 0xfd,
	0xba, 0x2d, 0xb5, 0xf5, 0x27, 0x00, 0x00, 0xff, 0xff, 0xd5, 0x6c, 0x1d, 0x8e, 0x2a, 0x07, 0x00,
	0x00,
}
