// Code generated by protoc-gen-go.
// source: github.com/appcelerator/amp/data/account/schema/account.proto
// DO NOT EDIT!

/*
Package schema is a generated protocol buffer package.

It is generated from these files:
	github.com/appcelerator/amp/data/account/schema/account.proto

It has these top-level messages:
	Account
	OrganizationMember
	Resource
	ResourceSettings
	Team
	TeamMember
	Permission
*/
package schema

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AccountType int32

const (
	AccountType_USER         AccountType = 0
	AccountType_ORGANIZATION AccountType = 1
)

var AccountType_name = map[int32]string{
	0: "USER",
	1: "ORGANIZATION",
}
var AccountType_value = map[string]int32{
	"USER":         0,
	"ORGANIZATION": 1,
}

func (x AccountType) String() string {
	return proto.EnumName(AccountType_name, int32(x))
}
func (AccountType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ResourceType int32

const (
	ResourceType_STACK   ResourceType = 0
	ResourceType_SERVICE ResourceType = 1
)

var ResourceType_name = map[int32]string{
	0: "STACK",
	1: "SERVICE",
}
var ResourceType_value = map[string]int32{
	"STACK":   0,
	"SERVICE": 1,
}

func (x ResourceType) String() string {
	return proto.EnumName(ResourceType_name, int32(x))
}
func (ResourceType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type GrantType int32

const (
	GrantType_READ   GrantType = 0
	GrantType_WRITE  GrantType = 1
	GrantType_DELETE GrantType = 3
	GrantType_ALL    GrantType = 4
)

var GrantType_name = map[int32]string{
	0: "READ",
	1: "WRITE",
	3: "DELETE",
	4: "ALL",
}
var GrantType_value = map[string]int32{
	"READ":   0,
	"WRITE":  1,
	"DELETE": 3,
	"ALL":    4,
}

func (x GrantType) String() string {
	return proto.EnumName(GrantType_name, int32(x))
}
func (GrantType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type Account struct {
	Id           string      `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	UserName     string      `protobuf:"bytes,2,opt,name=user_name,json=userName" json:"user_name,omitempty"`
	Type         AccountType `protobuf:"varint,3,opt,name=type,enum=schema.AccountType" json:"type,omitempty"`
	Email        string      `protobuf:"bytes,4,opt,name=email" json:"email,omitempty"`
	PasswordHash string      `protobuf:"bytes,5,opt,name=password_hash,json=passwordHash" json:"password_hash,omitempty"`
	IsVerified   bool        `protobuf:"varint,6,opt,name=is_verified,json=isVerified" json:"is_verified,omitempty"`
	CreateDt     int64       `protobuf:"varint,7,opt,name=create_dt,json=createDt" json:"create_dt,omitempty"`
}

func (m *Account) Reset()                    { *m = Account{} }
func (m *Account) String() string            { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()               {}
func (*Account) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Account) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Account) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *Account) GetType() AccountType {
	if m != nil {
		return m.Type
	}
	return AccountType_USER
}

func (m *Account) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Account) GetPasswordHash() string {
	if m != nil {
		return m.PasswordHash
	}
	return ""
}

func (m *Account) GetIsVerified() bool {
	if m != nil {
		return m.IsVerified
	}
	return false
}

func (m *Account) GetCreateDt() int64 {
	if m != nil {
		return m.CreateDt
	}
	return 0
}

type OrganizationMember struct {
	Id            string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	OrgAccountId  string `protobuf:"bytes,2,opt,name=org_account_id,json=orgAccountId" json:"org_account_id,omitempty"`
	UserAccountId string `protobuf:"bytes,3,opt,name=user_account_id,json=userAccountId" json:"user_account_id,omitempty"`
	CreateDt      int64  `protobuf:"varint,4,opt,name=create_dt,json=createDt" json:"create_dt,omitempty"`
}

func (m *OrganizationMember) Reset()                    { *m = OrganizationMember{} }
func (m *OrganizationMember) String() string            { return proto.CompactTextString(m) }
func (*OrganizationMember) ProtoMessage()               {}
func (*OrganizationMember) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *OrganizationMember) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *OrganizationMember) GetOrgAccountId() string {
	if m != nil {
		return m.OrgAccountId
	}
	return ""
}

func (m *OrganizationMember) GetUserAccountId() string {
	if m != nil {
		return m.UserAccountId
	}
	return ""
}

func (m *OrganizationMember) GetCreateDt() int64 {
	if m != nil {
		return m.CreateDt
	}
	return 0
}

type Resource struct {
	Id           string       `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	OrgAccountId string       `protobuf:"bytes,2,opt,name=org_account_id,json=orgAccountId" json:"org_account_id,omitempty"`
	TeamId       string       `protobuf:"bytes,3,opt,name=team_id,json=teamId" json:"team_id,omitempty"`
	Name         string       `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
	Type         ResourceType `protobuf:"varint,5,opt,name=type,enum=schema.ResourceType" json:"type,omitempty"`
	CreateDt     int64        `protobuf:"varint,6,opt,name=create_dt,json=createDt" json:"create_dt,omitempty"`
}

func (m *Resource) Reset()                    { *m = Resource{} }
func (m *Resource) String() string            { return proto.CompactTextString(m) }
func (*Resource) ProtoMessage()               {}
func (*Resource) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Resource) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Resource) GetOrgAccountId() string {
	if m != nil {
		return m.OrgAccountId
	}
	return ""
}

func (m *Resource) GetTeamId() string {
	if m != nil {
		return m.TeamId
	}
	return ""
}

func (m *Resource) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Resource) GetType() ResourceType {
	if m != nil {
		return m.Type
	}
	return ResourceType_STACK
}

func (m *Resource) GetCreateDt() int64 {
	if m != nil {
		return m.CreateDt
	}
	return 0
}

type ResourceSettings struct {
	Id         string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	ResourceId string `protobuf:"bytes,2,opt,name=resource_id,json=resourceId" json:"resource_id,omitempty"`
	Key        string `protobuf:"bytes,3,opt,name=key" json:"key,omitempty"`
	Value      string `protobuf:"bytes,4,opt,name=value" json:"value,omitempty"`
	CreateDt   int64  `protobuf:"varint,5,opt,name=create_dt,json=createDt" json:"create_dt,omitempty"`
}

func (m *ResourceSettings) Reset()                    { *m = ResourceSettings{} }
func (m *ResourceSettings) String() string            { return proto.CompactTextString(m) }
func (*ResourceSettings) ProtoMessage()               {}
func (*ResourceSettings) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ResourceSettings) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ResourceSettings) GetResourceId() string {
	if m != nil {
		return m.ResourceId
	}
	return ""
}

func (m *ResourceSettings) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ResourceSettings) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *ResourceSettings) GetCreateDt() int64 {
	if m != nil {
		return m.CreateDt
	}
	return 0
}

type Team struct {
	Id           string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	OrgAccountId string `protobuf:"bytes,2,opt,name=org_account_id,json=orgAccountId" json:"org_account_id,omitempty"`
	Name         string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Desc         string `protobuf:"bytes,4,opt,name=desc" json:"desc,omitempty"`
	CreateDt     int64  `protobuf:"varint,5,opt,name=create_dt,json=createDt" json:"create_dt,omitempty"`
}

func (m *Team) Reset()                    { *m = Team{} }
func (m *Team) String() string            { return proto.CompactTextString(m) }
func (*Team) ProtoMessage()               {}
func (*Team) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Team) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Team) GetOrgAccountId() string {
	if m != nil {
		return m.OrgAccountId
	}
	return ""
}

func (m *Team) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Team) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *Team) GetCreateDt() int64 {
	if m != nil {
		return m.CreateDt
	}
	return 0
}

type TeamMember struct {
	Id            string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	UserAccountId string `protobuf:"bytes,2,opt,name=user_account_id,json=userAccountId" json:"user_account_id,omitempty"`
	TeamId        string `protobuf:"bytes,3,opt,name=team_id,json=teamId" json:"team_id,omitempty"`
	CreateDt      int64  `protobuf:"varint,4,opt,name=create_dt,json=createDt" json:"create_dt,omitempty"`
}

func (m *TeamMember) Reset()                    { *m = TeamMember{} }
func (m *TeamMember) String() string            { return proto.CompactTextString(m) }
func (*TeamMember) ProtoMessage()               {}
func (*TeamMember) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *TeamMember) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TeamMember) GetUserAccountId() string {
	if m != nil {
		return m.UserAccountId
	}
	return ""
}

func (m *TeamMember) GetTeamId() string {
	if m != nil {
		return m.TeamId
	}
	return ""
}

func (m *TeamMember) GetCreateDt() int64 {
	if m != nil {
		return m.CreateDt
	}
	return 0
}

type Permission struct {
	Id         string    `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	TeamId     string    `protobuf:"bytes,2,opt,name=team_id,json=teamId" json:"team_id,omitempty"`
	ResourceId string    `protobuf:"bytes,3,opt,name=resource_id,json=resourceId" json:"resource_id,omitempty"`
	GrantType  GrantType `protobuf:"varint,4,opt,name=grant_type,json=grantType,enum=schema.GrantType" json:"grant_type,omitempty"`
	CreateDt   int64     `protobuf:"varint,5,opt,name=create_dt,json=createDt" json:"create_dt,omitempty"`
}

func (m *Permission) Reset()                    { *m = Permission{} }
func (m *Permission) String() string            { return proto.CompactTextString(m) }
func (*Permission) ProtoMessage()               {}
func (*Permission) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Permission) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Permission) GetTeamId() string {
	if m != nil {
		return m.TeamId
	}
	return ""
}

func (m *Permission) GetResourceId() string {
	if m != nil {
		return m.ResourceId
	}
	return ""
}

func (m *Permission) GetGrantType() GrantType {
	if m != nil {
		return m.GrantType
	}
	return GrantType_READ
}

func (m *Permission) GetCreateDt() int64 {
	if m != nil {
		return m.CreateDt
	}
	return 0
}

func init() {
	proto.RegisterType((*Account)(nil), "schema.Account")
	proto.RegisterType((*OrganizationMember)(nil), "schema.OrganizationMember")
	proto.RegisterType((*Resource)(nil), "schema.Resource")
	proto.RegisterType((*ResourceSettings)(nil), "schema.ResourceSettings")
	proto.RegisterType((*Team)(nil), "schema.Team")
	proto.RegisterType((*TeamMember)(nil), "schema.TeamMember")
	proto.RegisterType((*Permission)(nil), "schema.Permission")
	proto.RegisterEnum("schema.AccountType", AccountType_name, AccountType_value)
	proto.RegisterEnum("schema.ResourceType", ResourceType_name, ResourceType_value)
	proto.RegisterEnum("schema.GrantType", GrantType_name, GrantType_value)
}

func init() {
	proto.RegisterFile("github.com/appcelerator/amp/data/account/schema/account.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 612 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x94, 0xcf, 0x6e, 0xd3, 0x4c,
	0x14, 0xc5, 0x3b, 0xb1, 0xe3, 0x24, 0x37, 0x69, 0x3f, 0x7f, 0x43, 0x25, 0x2c, 0xb1, 0x68, 0x54,
	0x50, 0x09, 0x5d, 0x24, 0x08, 0xc4, 0x92, 0x85, 0xd5, 0x5a, 0xc5, 0xa2, 0xb4, 0xc8, 0x31, 0x45,
	0x62, 0x63, 0x4d, 0xed, 0xc1, 0x19, 0x51, 0xff, 0xd1, 0xcc, 0xa4, 0xa8, 0xdd, 0xb1, 0x63, 0xc7,
	0x53, 0xf0, 0x06, 0x3c, 0x0c, 0x8f, 0x83, 0x3c, 0xb6, 0x5b, 0x27, 0x69, 0xb3, 0xe8, 0x6e, 0xe6,
	0xce, 0xf5, 0xf5, 0x6f, 0xce, 0x39, 0x1a, 0x78, 0x1b, 0x33, 0x39, 0x9b, 0x9f, 0x8f, 0xc3, 0x2c,
	0x99, 0x90, 0x3c, 0x0f, 0xe9, 0x05, 0xe5, 0x44, 0x66, 0x7c, 0x42, 0x92, 0x7c, 0x12, 0x11, 0x49,
	0x26, 0x24, 0x0c, 0xb3, 0x79, 0x2a, 0x27, 0x22, 0x9c, 0xd1, 0xe4, 0x66, 0x3b, 0xce, 0x79, 0x26,
	0x33, 0x6c, 0x94, 0xd5, 0xdd, 0xbf, 0x08, 0x3a, 0x76, 0x79, 0x82, 0xb7, 0xa0, 0xc5, 0x22, 0x0b,
	0x0d, 0xd1, 0xa8, 0xe7, 0xb5, 0x58, 0x84, 0x9f, 0x40, 0x6f, 0x2e, 0x28, 0x0f, 0x52, 0x92, 0x50,
	0xab, 0xa5, 0xca, 0xdd, 0xa2, 0x70, 0x42, 0x12, 0x8a, 0x9f, 0x83, 0x2e, 0xaf, 0x72, 0x6a, 0x69,
	0x43, 0x34, 0xda, 0x7a, 0xf5, 0x68, 0x5c, 0xce, 0x1b, 0x57, 0xb3, 0xfc, 0xab, 0x9c, 0x7a, 0xaa,
	0x01, 0x6f, 0x43, 0x9b, 0x26, 0x84, 0x5d, 0x58, 0xba, 0x9a, 0x50, 0x6e, 0xf0, 0x53, 0xd8, 0xcc,
	0x89, 0x10, 0xdf, 0x33, 0x1e, 0x05, 0x33, 0x22, 0x66, 0x56, 0x5b, 0x9d, 0x0e, 0xea, 0xe2, 0x3b,
	0x22, 0x66, 0x78, 0x07, 0xfa, 0x4c, 0x04, 0x97, 0x94, 0xb3, 0xaf, 0x8c, 0x46, 0x96, 0x31, 0x44,
	0xa3, 0xae, 0x07, 0x4c, 0x9c, 0x55, 0x95, 0x82, 0x30, 0xe4, 0x94, 0x48, 0x1a, 0x44, 0xd2, 0xea,
	0x0c, 0xd1, 0x48, 0xf3, 0xba, 0x65, 0xe1, 0x50, 0xee, 0xfe, 0x42, 0x80, 0x4f, 0x79, 0x4c, 0x52,
	0x76, 0x4d, 0x24, 0xcb, 0xd2, 0x0f, 0x34, 0x39, 0xa7, 0x7c, 0xe5, 0x96, 0xcf, 0x60, 0x2b, 0xe3,
	0x71, 0x50, 0xc9, 0x13, 0xb0, 0xa8, 0xba, 0xea, 0x20, 0xe3, 0x71, 0x75, 0x1b, 0x37, 0xc2, 0x7b,
	0xf0, 0x9f, 0xd2, 0xa2, 0xd1, 0xa6, 0xa9, 0xb6, 0xcd, 0xa2, 0x7c, 0xdb, 0xb7, 0x40, 0xa4, 0x2f,
	0x11, 0xfd, 0x41, 0xd0, 0xf5, 0xa8, 0xc8, 0xe6, 0x3c, 0xa4, 0x0f, 0xe4, 0x78, 0x0c, 0x1d, 0x49,
	0x49, 0x72, 0xfb, 0x7f, 0xa3, 0xd8, 0xba, 0x11, 0xc6, 0xa0, 0x2b, 0x9f, 0x4a, 0x95, 0xd5, 0x1a,
	0x8f, 0x2a, 0x8f, 0xda, 0xca, 0xa3, 0xed, 0xda, 0xa3, 0x1a, 0xa1, 0x61, 0xd2, 0x02, 0xb6, 0xb1,
	0x84, 0xfd, 0x13, 0x81, 0x59, 0x7f, 0x33, 0xa5, 0x52, 0xb2, 0x34, 0x16, 0x2b, 0xf8, 0x3b, 0xd0,
	0xe7, 0x55, 0xcf, 0x2d, 0x3b, 0xd4, 0x25, 0x37, 0xc2, 0x26, 0x68, 0xdf, 0xe8, 0x55, 0x45, 0x5d,
	0x2c, 0x8b, 0x64, 0x5c, 0x92, 0x8b, 0x79, 0xcd, 0x5c, 0x6e, 0x16, 0x51, 0xda, 0x4b, 0x28, 0x3f,
	0x10, 0xe8, 0x3e, 0x25, 0xc9, 0x03, 0xd5, 0xab, 0x45, 0xd2, 0x1a, 0x22, 0x61, 0xd0, 0x23, 0x2a,
	0xc2, 0x5a, 0xb8, 0x62, 0xbd, 0x9e, 0xe1, 0x1a, 0xa0, 0x40, 0xb8, 0x27, 0x4e, 0x77, 0x04, 0xa5,
	0x75, 0x57, 0x50, 0xee, 0x35, 0x72, 0x6d, 0x82, 0x7e, 0x23, 0x80, 0x8f, 0x94, 0x27, 0x4c, 0x08,
	0x96, 0xa5, 0x2b, 0x3f, 0x6f, 0x0c, 0x6d, 0x2d, 0x0c, 0x5d, 0x72, 0x47, 0x5b, 0x71, 0xe7, 0x25,
	0x40, 0xcc, 0x49, 0x2a, 0x03, 0x15, 0x18, 0x5d, 0x05, 0xe6, 0xff, 0x3a, 0x30, 0x47, 0xc5, 0x89,
	0x4a, 0x4b, 0x2f, 0xae, 0x97, 0x6b, 0x35, 0xda, 0x7f, 0x01, 0xfd, 0xc6, 0x4b, 0x80, 0xbb, 0xa0,
	0x7f, 0x9a, 0x3a, 0x9e, 0xb9, 0x81, 0x4d, 0x18, 0x9c, 0x7a, 0x47, 0xf6, 0x89, 0xfb, 0xc5, 0xf6,
	0xdd, 0xd3, 0x13, 0x13, 0xed, 0xef, 0xc1, 0xa0, 0x19, 0x48, 0xdc, 0x83, 0xf6, 0xd4, 0xb7, 0x0f,
	0xde, 0x9b, 0x1b, 0xb8, 0x0f, 0x9d, 0xa9, 0xe3, 0x9d, 0xb9, 0x07, 0x8e, 0x89, 0xf6, 0xdf, 0x40,
	0xef, 0x86, 0xa3, 0x18, 0xe8, 0x39, 0xf6, 0xa1, 0xb9, 0x51, 0xb4, 0x7f, 0xf6, 0x5c, 0xdf, 0x31,
	0x11, 0x06, 0x30, 0x0e, 0x9d, 0x63, 0xc7, 0x77, 0x4c, 0x0d, 0x77, 0x40, 0xb3, 0x8f, 0x8f, 0x4d,
	0xfd, 0xdc, 0x50, 0xef, 0xdd, 0xeb, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xb7, 0x8b, 0x8f, 0xc5,
	0x30, 0x05, 0x00, 0x00,
}
